repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          [
            "--ignore=D100, D200, D205, D400, D401, D104, W503, W504,D401",
            "--max-line-length",
            "88",
          ]
        additional_dependencies:
          [
            "flake8-blind-except",
            "flake8-docstrings",
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-docstrings",
            "flake8-implicit-str-concat",
            "pydocstyle>=5.0.0",
          ]
# Explain the rules ignored:
# D100: Missing docstring in public module
# D104: Missing docstring in public package
# D200: One-line docstring should fit on one line with quotes
# D205: 1 blank line required between summary line and description
# D400: First line should end with a period
# D401: First line should be in imperative mood
# W503 and W504 is contradictory with each other
